version: "3.4"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/src:/steal-tracks/src
      # - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    ports:
      - 8080:8080
